Description: >
    This template deploys an Application Load Balancer that exposes our various ECS services.
    We create them it a seperate nested template, so it can be referenced by all of the other nested templates.

Parameters:
    VPCStackName:
        Type: String
        Description: Name of the VPC CF stack
    SGStackName:
        Type: String
        Description: Name of the Security Group stack

    # LoadBalancerCertificateArn:
    #     Type: String
    #     Default: 'arn:aws:acm:ap-southeast-2:123456789012:certificate/4e2017af-9197-46e0-83bf-49b910d37366'

Resources:

    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Ref AWS::StackName
            Subnets:
                Fn::Split:
                    - ","
                    - Fn::ImportValue:
                        !Sub "${VPCStackName}-PublicSubnets"
            SecurityGroups: 
                - Fn::ImportValue:
                    !Sub "${SGStackName}-LoadBalancerSecurityGroup"
            Tags: 
                - Key: Name
                  Value: !Ref AWS::StackName

    LoadBalancerListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            # Port: 443
            # Protocol: HTTPS
            Protocol: HTTP
            Port: 80
            DefaultActions: 
                - Type: forward
                  TargetGroupArn: !Ref DefaultTargetGroup
            # Certificates:
            #     - CertificateArn: !Ref LoadBalancerCertificateArn
    
    # We define a default target group here, as this is a mandatory Parameters
    # when creating an Application Load Balancer Listener. This is not used, instead
    # a target group is created per-service in each service template (../services/*)
    DefaultTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Sub ${AWS::StackName}-default
            VpcId:
                Fn::ImportValue:
                    !Sub "${VPCStackName}-VPC"
            Port: 80
            Protocol: HTTP
           
Outputs:

    LoadBalancer:
        Description: A reference to the Application Load Balancer
        Value: !Ref LoadBalancer
        Export:
            Name: !Sub "${AWS::StackName}-LoadBalancer"

    LoadBalancerUrl:
        Description: The URL of the ALB
        Value: !GetAtt LoadBalancer.DNSName
        Export:
            Name: !Sub "${AWS::StackName}-LoadBalancerUrl"

    Listener:
        Description: A reference to a port 80 listener
        Value: !Ref LoadBalancerListener
        Export:
            Name: !Sub "${AWS::StackName}-Listener"

    
