Description: >
    This template contains the security groups required by our entire stack.
    We create them in a seperate nested template, so they can be referenced
    by all of the other nested templates.

Parameters:
  VPCStackName:
    Type: String
    Description: Name of the VPC CF stack

Resources:

    # This security group defines who/where is allowed to access the ECS hosts directly.
    # By default we're just allowing access from the load balancer.  If you want to SSH 
    # into the hosts, or expose non-load balanced services you can open their ports here.
    ECSHostSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            VpcId:
                Fn::ImportValue:
                    !Sub "${VPCStackName}-VPC"
            GroupDescription: Access to the ECS hosts and the tasks/containers that run on them
            SecurityGroupIngress:
                # Only allow inbound access to ECS from the ELB
                - SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup 
                  IpProtocol: -1
            Tags: 
                - Key: Name
                  Value: !Sub ${AWS::StackName}-ECS-Hosts

    # This security group defines who/where is allowed to access the Application Load Balancer.
    # By default, we've opened this up to the public internet (0.0.0.0/0) but can you restrict
    # it further if you want.
    LoadBalancerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties: 
            VpcId:
                Fn::ImportValue:
                    !Sub "${VPCStackName}-VPC"
            GroupDescription: Access to the load balancer that sits in front of ECS
            SecurityGroupIngress:
                # Allow access from anywhere to our ECS services
                - CidrIp: 0.0.0.0/0
                  IpProtocol: -1
            Tags: 
                - Key: Name
                  Value: !Sub ${AWS::StackName}-LoadBalancers

    EFSMountTargetSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        VpcId:
            Fn::ImportValue:
                !Sub "${VPCStackName}-VPC"
        GroupDescription: "Security group to allow inbound NFS for EFS mount target from ECS container instances"
        SecurityGroupIngress:
          -
            IpProtocol: "tcp"
            FromPort: "2049"
            ToPort: "2049"
            CidrIp: 
                Fn::ImportValue:
                    !Sub "${VPCStackName}-VPCCidr"

Outputs:

    ECSHostSecurityGroup: 
        Description: A reference to the security group for ECS hosts
        Value: !Ref ECSHostSecurityGroup
        Export:
            Name: !Sub "${AWS::StackName}-ECSHostSecurityGroup"

    LoadBalancerSecurityGroup:
        Description: A reference to the security group for load balancers
        Value: !Ref LoadBalancerSecurityGroup
        Export:
            Name: !Sub "${AWS::StackName}-LoadBalancerSecurityGroup"
    
    EFSMountTargetSecurityGroup:
        Description: A reference to the security group for ECS hosts to access EFS
        Value: !Ref EFSMountTargetSecurityGroup
        Export:
            Name: !Sub "${AWS::StackName}-EFSMountTargetSecurityGroup"

